version: "3.9.7"

services:
  web:
    container_name: worksample_web
    restart: unless-stopped
    env_file:
      - ./worksample/.env
    build:
      context: ./worksample
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: bash -c "python3 /code/manage.py runserver 0.0.0.0:8000 &&
          echo "running" && tail -f /dev/null"
    volumes:
      - ./worksample/:/code
